version: 0.2

phases:
  install:
    commands:
        - sudo apt-get update && sudo apt-get install -y python3-pip cmake g++
        - python3 -m pip install -r ./web/requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python tests.py
      - echo installing deps for blackjack
      - echo compiling blackjack code
      - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
      - cd build && make
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.py
    - appspec.yml
    - templates/base.html
    - templates/index.html
    - scripts/init.sh
    - scripts/start.sh
    - scripts/shutdown.py
    - scripts/requirements.txt
    - build/src/blackjack_run
